#!/bin/bash

source $(dirname $0)/core/argue.sh
source $(dirname $0)/core/progress.sh

guide() {
	echo 'Find personal computer IP addresses by their MAC addresses'
	echo -e "\ua9 Sergeniously, 2021"
	echo 'Guide:'
}

argue internal "offer|--offer" of offer \
	as 'Print auto completion variants' -- $@
argue internal "guide|--guide|-h|--help|help|\?" of guide do guide \
	as 'Print this guide' -- $@
argue internal "usage|--usage" of usage \
	as 'Print short usage' -- $@
argue internal "setup|--setup" do argue-setup \
	as 'Install auto completion' -- $@
argue required --mac ... of MAC to macs[] ~ "([a-fA-F0-9]{1,2}:){5}[a-fA-F0-9]{1,2}" \
	as 'MAC addresses to find' -- $@
argue optional --net of IP to net ~ "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" or '192.168.111' \
	as 'IP prefix of network to scan' -- $@
argue optional --min of number to min ? '[0..255]' or 0 \
	as 'Minimal position to start' -- $@
argue optional --max of number to max ? '[0..255]' or 255 \
	as 'Maximal position to stop' -- $@
argue optional --no-scan to do_scan = false or true \
	as 'Proceed without scanning?' -- $@
[[ $? -ge 200 ]] && echo && exit

if $do_scan; then
	for (( ip = $min; ip <= $max; ip++ )); do
		progress in 'Scanning IP addresses' is $(( $ip - $min )) of $(( $max - $min )) as '[!.]'
		ping -c 1 -W 1 -q $net.$ip &> /dev/null
	done
	echo
fi

pcs=()
while read line; do
	for mac in ${macs[*]}; do
		if [[ $line =~ ^.*\(([0-9.]+)\)\ at\ $mac.*$ ]]; then
			ip=${BASH_REMATCH[1]}
			pcs+=("$ip $mac")
		fi
	done
done < <(arp -a)

if (( ${#pcs[@]} )); then
	printf "Found a computer IP %s with MAC %s\n" ${pcs[*]}
	exit 0
fi

echo "No computer has been found"
exit 1
