#!/usr/bin/env bash

source $(dirname $0)/core/git.sh
source $(dirname $0)/core/argue.sh
source $(dirname $0)/core/proceed.sh

if [[ -f $GIT_DIR/topics ]]; then
	read known_topics < <(cat $GIT_DIR/topics)
fi

about() {
	echo 'Push local commits to code review for a current or specific branch with specific topics'
	echo -e '\ua9 Belenkov Sergei, 2021 <https://github.com/sergeniously/shmart>'
}

setup-topics() {
	if ((${#topics[@]})); then
		if echo "${topics[*]}" > $GIT_DIR/topics; then
			echo "Topics '${topics[*]}' are known now for the current repository"
		fi
	fi
	exit 0
}

argue initiate "$@"
argue defaults offer guide usage setup
argue optional install do setup-topics to do_install = true or false \
	as 'Make topics known for the repository'
argue optional --branch of BRANCH to branch ~ "[0-9A-Za-z]+" or "$GIT_BRANCH" @ git-offer-branch \
	as 'Branch to push commits for'
for topic in $known_topics; do
	argue optional /$topic to topics[] = $topic as 'Additional preset topic to push commits with'
done
argue optional "/([0-9A-Za-z_-]+)" of topic ... to topics[] \
	as 'Additional custom topic to push commits with'
argue finalize

while [[ ! $branch || $branch == HEAD ]]; do
	read -p "Input target branch: " -e branch
done

topics=$(IFS=/; echo "${topics[*]}")

proceed to 'update local branch' \
	do 'git pull --rebase' or die

proceed to 'push commits for review' \
	do "git push origin HEAD:refs/for/${branch}${topics:+%topic=$topics}"
